server:
  port: 8010

spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false

# Secret access token
token: ${SECRET_TOKEN}